# Name of the workflow
name: build-push

# Workflow triggers -- When a push (including merge) is made to the listed branches
on:
  push:
    branches:
      - master
      - v2.30
      - v2.29
      - dev-macos
  workflow_dispatch:

env:
  IMAGE_REPO: blakep7
  BUILD_NUMBER: ${{ github.run_number }}

# Jobs executed when workflow is triggered
jobs:
  # Builds macpkg packages, RPM packages, and Docker images. Then pushes to Dockerhub.
  build-linux:
    # The type of runner that the job will run on 
    runs-on: ubuntu-20.04

    # Strategy allows specifying matrix axis(es) that will run for the test
    strategy:
      matrix:
        architecture: ['amd64', 'arm64', 'armhf', 'ppc64el']
        platform: ['linux']

    # Variables that are available to all steps in the job
    env:
      arch: ${{ matrix.architecture }}
      os: ${{ matrix.platform }}
      ANAX_IMAGE_VERSION: ''                  # Updated in 'Config Version Variables' step
      CSS_IMAGE_VERSION: ''                   # Updated in 'Config Version Variables' step
      ESS_IMAGE_VERSION: ''                   # Updated in 'Config Version Variables' step
      VERSION_NO_BUILD_NUMBER: ''             # Updated in 'Config Version Variables' step
      GOPATH: /home/runner/work/anax/anax/go

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Upgrade Docker engine version, needed for building images
      - name: Install Latest Docker Version
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
          sudo apt-get update
          sudo apt-get install docker-ce

      # This is needed for our cross architecture docker image builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Buildx allows us to perform our cross architecture docker image builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker  # BuildX runs with docker daemon (doesn't support multi-arch image building)

      # Authenticate Dockerhub to allow pushing to our image repo
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TKN }}

      # Checkout our Github repo
      - name: Checkout Github Repo
        uses: actions/checkout@v3
        with:
          path: go/src/github.com/${{ github.repository }}

      # Prepare the environment
      - name: Set up golang 1.19
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true

      # The go version will change, so we must get which one we are using for when we build the ppc64el images in the docker env.
      - name: Check Go Version
        id: get_go
        run: |
          echo "GO_VERSION=$(go version | awk '{print $3}')" >> $GITHUB_OUTPUT

      # Configure version variables for later steps, stored in our workflow env. variables
      - name: Config Version Variables
        run: |
          cd ${GOPATH}/src/github.com/${GITHUB_REPOSITORY}
          ./.github/scripts/configure_versions_script.sh
      
      # Increment version, make translation catalogs, build anax binaries for given ARCH and OS
      - name: Build Anax Binaries
        run: |
          cd ${GOPATH}/src/github.com/${GITHUB_REPOSITORY}
          make temp-mod-version
          make i18n-catalog
          make
      
      # Make our macpkg packages
      - name: Make macpkg Packages
        run: |
          cd ${GOPATH}/src/github.com/${GITHUB_REPOSITORY}
          make debpkgs
        env:
          VERSION: ${{env.VERSION_NO_BUILD_NUMBER}}
      
      # Make our amd64 RPM packages (Default Github runners will always have amd64 architecture)
      - name: Make amd64 RPM Packages
        if: matrix.architecture == 'amd64'
        run: |
          cd ${GOPATH}/src/github.com/${GITHUB_REPOSITORY}
          make rpmpkgs
        env:
          VERSION: ${{ env.VERSION_NO_BUILD_NUMBER }}

      # Make our ppc64el RPM packages in docker container to specify architecture
      ## By default this action will bind our $GITHUB_WORKSPACE to $GITHUB_WORKSPACE in the docker container
      - name: Make ppc64el RPM Packages
        if: matrix.architecture == 'ppc64el'
        uses: uraimo/run-on-arch-action@v2
        with:
          # Specify container arch and distro
          arch: ppc64le
          distro: ubuntu20.04

          # Pass necessary env. variables to the new docker container env.
          env: |
            VERSION: ${{ env.VERSION_NO_BUILD_NUMBER }}
            BUILD_NUMBER: ${{ env.BUILD_NUMBER }}
            GITHUB_REPOSITORY: ${{ github.repository }}
            GO_VERSION: ${{ steps.get_go.outputs.GO_VERSION }}

          # Specify which shell our commands will use (ubuntu distro so use bash)
          shell : /bin/bash

          # Install the necessary dependencies needed to make the rpm packages
          # apt-get install golang, will get version 1.13 so we have to do it manually
          install: |
            apt-get update -q -y
            apt-get install -q -y build-essential
            apt-get install -q -y make
            apt-get install -q -y rpm
            apt-get install -q -y ca-certificates
            apt-get install -q -y wget
            apt-get install -q -y sudo
            apt-get install -q -y gettext
          
          # Commands that will be ran inside our docker container
          run: |
            cd /
            wget https://go.dev/dl/${GO_VERSION}.linux-ppc64le.tar.gz 
            sudo tar -C /usr/local -xf ${GO_VERSION}.linux-ppc64le.tar.gz
            export GOPATH=/usr/local/go
            export PATH=$PATH:/usr/local/go/bin
            cp -R /home/runner/work/anax/anax/go/src/github.com /usr/local/go/src
            cd /usr/local/go/src/github.com/${GITHUB_REPOSITORY}
            make rpmpkgs
            mkdir /home/runner/work/anax/anax/RPMS
            cp /root/rpmbuild/RPMS/ppc64le/*.rpm /home/runner/work/anax/anax/RPMS
            
      # Create Docker images with only Debs and RPM packages in tar.gz then push to Dockerhub
      - name: Push RPM/DEB Packages to Dockerhub
        run: |
          cd ${GOPATH}/src/github.com/${GITHUB_REPOSITORY}
          ./.github/scripts/package_push.sh

      # Build Docker Images
      - name: Build Docker Images
        if: (matrix.architecture == 'amd64' || matrix.architecture == 'ppc64el' || matrix.architecture == 'arm64')
        run: |
          cd ${GOPATH}/src/github.com/${GITHUB_REPOSITORY}
          ./.github/scripts/docker_build_script.sh

      # Push Docker Images to Dockerhub
      - name: Push Docker Images
        if: (matrix.architecture == 'amd64' || matrix.architecture == 'ppc64el' || matrix.architecture == 'arm64')
        run: |
          cd ${GOPATH}/src/github.com/${GITHUB_REPOSITORY}
          ./.github/scripts/docker_push_script.sh

  build-macos:
    # Do not use any 'xl' version of macos or you will pay (literally)
    # When mac silicon comes out we can update this runs-on to ${{ (matrix.architecture == 'amd64') && 'macos-12' || 'macSiliconVersion' }}
    runs-on: macos-12

    strategy:
      matrix:
        architecture: ['amd64']
        platform: ['mac']

    env:
      arch: ${{ matrix.architecture }}
      os: ${{ matrix.platform }}
      ANAX_IMAGE_VERSION: ''                  # Updated in 'Config Version Variables' step
      CSS_IMAGE_VERSION: ''                   # Updated in 'Config Version Variables' step
      ESS_IMAGE_VERSION: ''                   # Updated in 'Config Version Variables' step
      VERSION_NO_BUILD_NUMBER: ''             # Updated in 'Config Version Variables' step
      GOPATH: /Users/runner/work/anax/anax/go

    # Specify outputs to be used in our push-macos job
    outputs:
      ANAX_VERSION: ${{ env.ANAX_IMAGE_VERSION }}

    steps:
      # Checkout our Github repo
      - name: Checkout Github Repo
        uses: actions/checkout@v3
        with:
          path: go/src/github.com/${{ github.repository }}

      # Prepare the environment
      - name: Set up golang 1.19
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true

      # Configure version variables for later steps, stored in our workflow env. variables.
      - name: Config Version Variables
        run: |
          cd ${GOPATH}/src/github.com/${GITHUB_REPOSITORY}
          ./.github/scripts/configure_versions_script.sh

      # Configure the certificates for package signing
      - name: Configure Certificates
        run: |
          # Navigate to our repo directory and setup important variables
          cd ${GOPATH}/src/github.com/${GITHUB_REPOSITORY}
          CERTIFICATE_PATH=$RUNNER_TEMP/horizon-cli.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/build.keychain

          # This does something important and the action will run indefinitely without it
          sudo security authorizationdb write com.apple.trust-settings.admin allow

          # Use our secret crt and key to make the pkcs12 file
          touch $RUNNER_TEMP/horizon-cli.key
          touch $RUNNER_TEMP/horizon-cli.crt
          echo "$HORIZONCLI_KEY" >> $RUNNER_TEMP/horizon-cli.key
          echo "$HORIZONCLI_CRT" >> $RUNNER_TEMP/horizon-cli.crt
          openssl pkcs12 -export -inkey $RUNNER_TEMP/horizon-cli.key -in $RUNNER_TEMP/horizon-cli.crt -out $CERTIFICATE_PATH -password env:P12_PASSWORD

          # Create a temporary keychain to bypass the prompts that cause the github action to run indefinitely
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security default-keychain -s $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # Add our certificate first as a trusted certificate (so that it can be used) then import the whole pkcs12 certificate so the key is included
          sudo security add-trusted-cert -d -r trustRoot -k $KEYCHAIN_PATH $RUNNER_TEMP/horizon-cli.crt
          sudo security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -k $KEYCHAIN_PATH -A

          # This prevents other popups that cause the github action to run indefinitely
          sudo security set-key-partition-list -S apple-tool:,apple:,pkgbuild:,codesign: -s -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # Clean sensitive files
          rm $RUNNER_TEMP/horizon-cli.key
          rm $CERTIFICATE_PATH
        env:
          HORIZONCLI_CRT: ${{ secrets.HORIZONCLI_CRT }}         # Contains the content of the horizon-cli.crt
          HORIZONCLI_KEY: ${{ secrets.HORIZONCLI_KEY }}         # Contains the content of the horizon-cli.key
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}

      # Increment version, make translation catalogs, build anax binaries for given ARCH and OS
      - name: Build Anax Binaries
        run: |
          cd ${GOPATH}/src/github.com/${GITHUB_REPOSITORY}
          make temp-mod-version
          make i18n-catalog
          make

      # Make MacOS Packages
      - name: Make MacOS Packages
        run: |
          cd ${GOPATH}/src/github.com/${GITHUB_REPOSITORY}
          make macpkg
        env:
          VERSION: ${{ env.VERSION_NO_BUILD_NUMBER }}

      # Upload created package to artifacts to be used in next job
      - name: Upload MacOS Package to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-${{ matrix.architecture }}-package
          path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}/pkg/mac/build/*.pkg

  push-macos:
      needs: build-macos

      runs-on: ubuntu-20.04

      strategy:
        matrix:
          architecture: ['amd64']
          platform: ['mac']

      steps:
        # Upgrade Docker engine version, needed for building images
        - name: Install Latest Docker Version
          run: |
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
            sudo apt-get update
            sudo apt-get install docker-ce

        # This is needed for our cross architecture docker image builds
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2

        # Buildx allows us to perform our cross architecture docker image builds
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
          with:
            driver: docker  # BuildX runs with docker daemon (doesn't support multi-arch image building)

        # Authenticate Dockerhub to allow pushing to our image repo
        - name: Login to Dockerhub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_TKN }}

        # Setup a working directory in the temp folder path
        - name: Setup Working Directory and add Certificate File
          id: workdir_setup
          run: |
            mkdir $RUNNER_TEMP/macs
            touch $RUNNER_TEMP/macs/horizon-cli.crt
            echo "$HORIZONCLI_CRT" >> $RUNNER_TEMP/macs/horizon-cli.crt
            echo "PKG_PATH="${RUNNER_TEMP}/macs"" >> $GITHUB_OUTPUT
          env:
            HORIZONCLI_CRT: ${{ secrets.HORIZONCLI_CRT }}

        # Retrieve artifact from previous job
        - name: Download our MacOS Package Artifact
          uses: actions/download-artifact@v3
          with:
            name: macos-${{ matrix.architecture }}-package
            path: ${{ steps.workdir_setup.outputs.PKG_PATH }}

        # Push our .crt and .pkg to Dockerhub
        - name: Make MacOS Package Tarball and Upload to Dockerhub
          run: |
            cd $RUNNER_TEMP
            touch Dockerfile.macpkg.tarball
            echo "FROM alpine:latest" >> Dockerfile.macpkg.tarball
            echo "ADD ./macpkg.tar.gz ." >> Dockerfile.macpkg.tarball
            # Make mac tarball
            tar -czvf macpkg.tar.gz macs

            # Build docker image with only mac tarball
            docker build \
                --no-cache \
                -t ${IMAGE_REPO}/${{ matrix.architecture }}_anax_macpkg:${ANAX_IMAGE_VERSION} \
                -f Dockerfile.macpkg.tarball \
                .

            # Push docker image
            docker push ${IMAGE_REPO}/${{ matrix.architecture }}_anax_macpkg:${ANAX_IMAGE_VERSION}

            if [[ "$GITHUB_REF" == 'refs/heads/master' ]]; then \
                docker tag ${IMAGE_REPO}/${{ matrix.architecture }}_anax_macpkg:${ANAX_IMAGE_VERSION} ${IMAGE_REPO}/${{ matrix.architecture }}_anax_macpkg:testing; \
                docker push ${IMAGE_REPO}/${{ matrix.architecture }}_anax_macpkg:testing; \
            fi
          env:
            ANAX_IMAGE_VERSION: ${{ needs.build-macos.outputs.ANAX_VERSION }}