name: Anax Release Manager

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-20.04

    environment: release_environment

    steps:
      - name: Test
        run: |
          echo "Hello World"