name: Anax Release Manager

on:
  push:     # Remove for PR
  workflow_dispatch:
  repository_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-20.04

    environment: release_environment

    env:
      IMAGE_REPO: ${{ vars.DOCKERHUB_REPO }}
      GITHUB_CONTAINER_REGISTRY: ${{ github.repository_owner }}

    steps:
      # Ensure that the repo variables and secrets are set before running any other steps
      - name: Check User Set Variables
        run: |
          if [[ -z "$DOCKER_USER" ]]; then \
          echo "::error::Secret DOCKER_USER was not set"; \
          exit 1; \
          fi
          if [[ -z "$DOCKER_TOKEN" ]]; then \
          echo "::error::Secret DOCKER_TOKEN was not set"; \
          exit 1; \
          fi
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

      # Upgrade Docker engine version
      - name: Install Latest Docker Version
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
          sudo apt-get update
          sudo apt-get install docker-ce

      # Authenticate Dockerhub to allow pushing to our image repo
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }} 
          
      # Authenticate GHCR to allow pushing to our alternate image registry
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Checkout our Github repo
      - name: Checkout Github Repo
        uses: actions/checkout@v3

      # Promote release tags to Dockerhub
      - name: Promote 'release' tags to Dockerhub
        run: |
          echo Placeholder
        env:
          FROM_REGISTRY: #GHCR
          TO_REGISTRY: #DCKRHUB
          FROM_TAG: #TESTING
          TO_TAG: #LATEST

      # Promote latest tags to Dockerhub
      - name: Promote 'latest' tags to Dockerhub
        run: |
          echo Placeholder
        env:
          FROM_REGISTRY: #GHCR
          TO_REGISTRY: #DCKRHUB
          FROM_TAG: #TESTING
          TO_TAG: #LATEST


      # Get Packages


      # Create GH release page